version: '3.9'
services:
  api:
    container_name: 'clean-ts-upload'
    image: node:18
    working_dir: /usr/src/clean-ts-upload
    command: bash -c "npm install --omit=dev && npm run debug"
    restart: always
    environment:
      - HUSKY=0
    volumes:
      - ./dist/:/usr/src/clean-ts-upload/dist/
      - ./tmp/:/usr/src/clean-ts-upload/tmp/
      - ./.env:/usr/src/clean-ts-upload/.env
      - ./package.json:/usr/src/clean-ts-upload/package.json
    ports:
      - 3000:3000
      - 9229:9229
